// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicWebAPI.Data;

#nullable disable

namespace MusicWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220505105733_more Seeding data")]
    partial class moreSeedingdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MusicClassLibrary.Entities.AlbumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Name = "JORDI"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            Name = "Red Pill Blues"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            Name = "Honey"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            Name = "Do It Again"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 1,
                            Name = "V"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 3,
                            Name = "The 20/20 Experience"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 4,
                            Name = "cure"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 2,
                            Name = "Dancing on My Own"
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 5,
                            Name = "Raise!"
                        });
                });

            modelBuilder.Entity("MusicClassLibrary.Entities.ArtistEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Maroon 5"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Robyn"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Justin Timberlake"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SIRUP"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Earth, Wind & Fire"
                        });
                });

            modelBuilder.Entity("MusicClassLibrary.Entities.SongEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 4,
                            ArtistId = 1,
                            Length = "3:09",
                            Name = "Memories"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 4,
                            ArtistId = 1,
                            Length = "2:52",
                            Name = "Lost"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 6,
                            ArtistId = 3,
                            Length = "5:26",
                            Name = "Suit & Tie"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 3,
                            ArtistId = 2,
                            Length = "4:05",
                            Name = "Between the Lines"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 1,
                            ArtistId = 5,
                            Length = "4:48",
                            Name = "Boogie Wonderland"
                        });
                });

            modelBuilder.Entity("MusicClassLibrary.Entities.AlbumEntity", b =>
                {
                    b.HasOne("MusicClassLibrary.Entities.ArtistEntity", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicClassLibrary.Entities.SongEntity", b =>
                {
                    b.HasOne("MusicClassLibrary.Entities.AlbumEntity", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicClassLibrary.Entities.ArtistEntity", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicClassLibrary.Entities.AlbumEntity", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicClassLibrary.Entities.ArtistEntity", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
